# Listen on default MQTT port
listener 1883

# For now we allow anonymous (easier to test).
# We can secure this later with usernames/passwords.
allow_anonymous true

persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
